base_directory: /gstock/GeneIso/
# base_directory: TO_CHANGE
External:
  biomart_ensembl: data/External/ENSEMBL/mart_export.txt.gz
  biomart_ensembl_exons: data/External/ENSEMBL/mart_export_exon_38.txt.gz

EXPRESSION:
  base_directory: /gstock/biolo_datasets/variation/benchmark/Databases/GTEX/V8/RNA_Seq_data/
  External:
    transcript_reads: GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_transcript_expected_count.gct.gz
    transcript_tpm: GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_transcript_tpm.gct.gz
  Final:
    transcript_check: /gstock/EXOTIC/data/EXPRESSION/GTEx_V8_transcript_checking.gct.gz
